# Generated by Django 4.2.17 on 2026-04-04 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('calculated_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.plantier')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
