# Generated by Django 4.2.11 on 2026-03-20 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisruptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('heavy_rain', 'Heavy Rain'), ('extreme_heat', 'Extreme Heat'), ('severe_aqi', 'Severe AQI'), ('flash_flood', 'Flash Flood'), ('curfew_strike', 'Curfew or Strike'), ('platform_down', 'Platform Down')], max_length=32)),
                ('severity_value', models.FloatField(default=0.0)),
                ('threshold_value', models.FloatField(default=0.0)),
                ('is_full_trigger', models.BooleanField(default=True)),
                ('claims_generated', models.BooleanField(default=False)),
                ('affected_platform', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source_api', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disruptions', to='zones.zone')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
