# Generated by Django 4.2.11 on 2026-03-20 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('imps', 'IMPS'), ('neft', 'NEFT')], default='upi', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('pending', 'Pending'), ('credited', 'Credited'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='queued', max_length=20)),
                ('utr_number', models.CharField(blank=True, max_length=80)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_fund_acct_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='claims.claim')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
