# Generated by Django 4.2.11 on 2026-03-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.PositiveSmallIntegerField(choices=[(1, 'Layer 1'), (2, 'Layer 2'), (3, 'Layer 3'), (4, 'Layer 4'), (5, 'Layer 5'), (6, 'Layer 6')], default=1)),
                ('flag_type', models.CharField(max_length=80)),
                ('score_contribution', models.FloatField(default=0.0)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag_records', to='claims.claim')),
            ],
            options={
                'ordering': ['layer', 'created_at'],
            },
        ),
    ]
