# Generated by Django 4.2.11 on 2026-04-17 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudflag',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['claim', 'is_deleted'], name='fraud_fraud_claim_i_c8587f_idx'),
        ),
    ]
