# Generated by Django 4.2.11 on 2026-03-20 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('rain_probability', models.FloatField(default=0.0)),
                ('heat_probability', models.FloatField(default=0.0)),
                ('aqi_probability', models.FloatField(default=0.0)),
                ('disruption_probability', models.FloatField(default=0.0)),
                ('overall_risk_level', models.CharField(default='Low', max_length=20)),
                ('forecasted_rain_mm', models.FloatField(default=0.0)),
                ('forecasted_temp_c', models.FloatField(default=0.0)),
                ('forecasted_aqi', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='zones.zone')),
            ],
            options={
                'ordering': ['-forecast_date', 'zone__city'],
                'unique_together': {('zone', 'forecast_date')},
            },
        ),
    ]
