# Generated by Django 4.2.11 on 2026-03-20 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('amazon', 'Amazon Flex'), ('zepto', 'Zepto'), ('blinkit', 'Blinkit'), ('dunzo', 'Dunzo'), ('other', 'Other')], default='other', max_length=20)),
                ('segment', models.CharField(choices=[('bike', 'Bike'), ('bicycle', 'Bicycle'), ('auto', 'Auto Rickshaw'), ('car', 'Car')], default='bike', max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_updated_at', models.DateTimeField(blank=True, null=True)),
                ('grace_tokens', models.PositiveIntegerField(default=0)),
                ('razorpay_contact_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_fund_acct_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_mandate_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workerprofile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='zones.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
